using ChaturbateRecorderApp.Services;
using Xunit;

namespace ChaturbateRecorderApp.Tests
{
    /// <summary>
    /// Contrôle du cookies.txt avant enregistrement du réglage.
    ///
    /// Les cas ne sont pas imaginés : ils viennent d'un fichier réel qui a fait
    /// échouer TOUS les enregistrements pendant plusieurs jours sans que la
    /// cause soit visible, le 2026-08-05. Valeurs remplacées par des factices.
    /// </summary>
    public class CookieFileValidatorTests
    {
        private const string Header = "# Netscape HTTP Cookie File";

        private static string Line(string domain, string flag = "TRUE", string name = "sessionid")
            => $"{domain}\t{flag}\t/\tTRUE\t1791052637\t{name}\tFAKE";

        [Fact]
        public void AWellFormedFileIsAccepted()
        {
            var r = CookieFileValidator.Validate(new[]
            {
                Header,
                "# This file was generated by Cookie-Editor",
                "#HttpOnly_" + Line(".chaturbate.com"),
                Line(".chaturbate.com", name: "csrftoken"),
            });

            Assert.True(r.IsValid);
        }

        /// <summary>
        /// LE cas réel. « HttpOnly_ » sans le « # » : Python ne reconnaît pas le
        /// préfixe, ne saute pas la ligne comme un commentaire, et bute sur un
        /// domaine « HttpOnly_.chaturbate.com » qui ne commence pas par un point
        /// alors que l'indicateur vaut TRUE. Cinq cookies sur six étaient dans
        /// ce cas, dont sessionid.
        /// </summary>
        [Fact]
        public void TheMissingHashBeforeHttpOnlyIsReported()
        {
            var r = CookieFileValidator.Validate(new[]
            {
                Header,
                "HttpOnly_" + Line(".chaturbate.com"),
            });

            Assert.Equal(CookieFileProblem.HttpOnlyPrefixMissingHash, r.Problem);
            Assert.Equal(2, r.Line);
        }

        /// <summary>
        /// L'invariant que http.cookiejar impose par une assertion — c'est lui
        /// qui faisait echouer le fichier une fois le prefixe retire.
        /// </summary>
        [Theory]
        [InlineData("chaturbate.com", "TRUE")]
        [InlineData(".chaturbate.com", "FALSE")]
        public void DomainAndSubdomainFlagMustAgree(string domain, string flag)
        {
            var r = CookieFileValidator.Validate(new[] { Header, Line(domain, flag) });
            Assert.Equal(CookieFileProblem.DomainFlagMismatch, r.Problem);
        }

        [Theory]
        [InlineData("chaturbate.com", "FALSE")]
        [InlineData(".chaturbate.com", "TRUE")]
        public void BothConsistentCombinationsAreAccepted(string domain, string flag)
        {
            Assert.True(CookieFileValidator.Validate(new[] { Header, Line(domain, flag) }).IsValid);
        }

        /// <summary>
        /// Python vérifie la ligne magique avant toute autre chose et refuse le
        /// fichier entier sans elle : un export JSON échoue ici, pas plus loin.
        /// </summary>
        [Fact]
        public void TheNetscapeHeaderIsRequired()
        {
            var r = CookieFileValidator.Validate(new[] { Line(".chaturbate.com") });
            Assert.Equal(CookieFileProblem.MissingNetscapeHeader, r.Problem);
        }

        [Fact]
        public void AHeaderWithoutAnyCookieIsEmpty()
        {
            var r = CookieFileValidator.Validate(new[] { Header, "# rien d'autre", "" });
            Assert.Equal(CookieFileProblem.Empty, r.Problem);
        }

        [Fact]
        public void ATruncatedLineIsReportedWithItsNumber()
        {
            var r = CookieFileValidator.Validate(new[] { Header, ".chaturbate.com\tTRUE\t/\tTRUE" });
            Assert.Equal(CookieFileProblem.TooFewFields, r.Problem);
            Assert.Equal(2, r.Line);
        }

        /// <summary>
        /// Les fins de ligne Windows ne doivent PAS faire echouer la validation :
        /// mesure faite le 2026-08-05, un fichier CRLF converti en LF etait
        /// rejete exactement pareil — ce n'etait donc pas la cause, et refuser
        /// CRLF ici enverrait l'utilisateur sur une fausse piste.
        /// </summary>
        [Fact]
        public void WindowsLineEndingsAreNotAProblem()
        {
            var r = CookieFileValidator.Validate(new[] { Header + "\r", "#HttpOnly_" + Line(".chaturbate.com") + "\r" });
            Assert.True(r.IsValid);
        }

        [Fact]
        public void AnEmptyOrNullInputIsReportedRatherThanThrowing()
        {
            Assert.Equal(CookieFileProblem.MissingNetscapeHeader,
                CookieFileValidator.Validate(new string[0]).Problem);
            Assert.Equal(CookieFileProblem.MissingNetscapeHeader,
                CookieFileValidator.Validate(null!).Problem);
        }
    }
}
